apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ .Values.kustomizeNamespace }}
helmGlobals:
  chartHome: {{ .Values.chartHome }}
helmCharts:
- name: {{ .Values.chartName }}
  releaseName: {{ .Values.chartreleaseName }}
  namespace: {{ .Values.chartNamespace }}
  valuesFile: {{ .Values.chartvalueFiles }}
  includeCRDs: {{ .Values.chartincludeCRDs }}
