apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  type: vcluster
  tenant: mt-dev-1F20D
  env: dev
helmGlobals:
  chartHome: ../../../../charts
helmCharts:
- name: vcluster
  releaseName: vmt-dev-1f20d
  valuesFile: values.yaml
  namespace: mt-hns-1F20D

